#!/bin/sh
cd "$(dirname "$0")"

eval "$(conda shell.bash hook)"
conda activate ./.env 
python render.py 

export GIT_COMMITTER_NAME="Auto-Andy Jones" 
export GIT_COMMITTER_EMAIL="andyjones.ed+auto@gmail.com"
export GIT_AUTHOR_NAME="Auto-Andy Jones" 
export GIT_AUTHOR_EMAIL="andyjones.ed+auto@gmail.com"

git commit -am "Update"
git push
git checkout gh-pages && git merge --no-edit master && git push && git checkout master
